name: Testing

on: [push, pull_request]

jobs:
  run-backend-tests:
    name: Backend tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: json, dom, curl, libxml, mbstring
        coverage: none
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    - name: Copy .env
      run: cp .env.testing .env
    - name: Create Database
      run: |
          sudo systemctl start mysql
          mysql --user="root" --password="root" -e "CREATE DATABASE cypress character set UTF8mb4 collate utf8mb4_bin;"
          mysql --user="root" --password="root" -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root'";
    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Run Laravel Server
      run: php artisan serve > /dev/null 2>&1 &
    - name: Install Node Dependencies
      run: npm ci
    - name: Execute tests
      run: npm run cy:run
  run-frontend-tests:
    name: Frontend tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: json, dom, curl, libxml, mbstring
        coverage: none
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    - name: Copy .env
      run: cp .env.testing .env
    - name: Create Database
      run: |
          sudo systemctl start mysql
          mysql --user="root" --password="root" -e "CREATE DATABASE cypress character set UTF8mb4 collate utf8mb4_bin;"
          mysql --user="root" --password="root" -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root'";
    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Run Laravel Server
      run: php artisan serve > /dev/null 2>&1 &
    - name: Copy Frontend .env
      run: cp frontend/.env.testing frontend/.env
    - name: Install Node Dependencies
      run: cd frontend && npm ci
    - name: Execute tests
      run: cd frontend && npm run cy:test
